<?php if (!defined('TL_ROOT')) die('You cannot access this file directly!');

/**
 * Contao Open Source CMS
 * Copyright (C) 2005-2011 Leo Feyer
 *
 * Formerly known as TYPOlight Open Source CMS.
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program. If not, please visit the Free
 * Software Foundation website at <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 * @copyright  Nils Heinold 
 * @author     Nils Heinold
 * @package    Language
 * @license    LGPL 
 * @filesource
 */


/**
 * Miscellaneous
 */
// Counter
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_all_title']       = 'visitors whole';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_month_title']     = 'visitors month';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_today_title']     = 'visitors today';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_yesterday_title'] = 'visitors yesterday';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_online_title']    = 'visitors online';


/**
 * Texte
 */
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum']  = "<p><strong>Analytics by PIWIK!<br /></strong>";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "This website uses Piwik, a web analytics open-source software.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "Piwik uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "The information generated by the cookie about your use of the website (including your IP address anonymized prior to its storage) will be stored on the server of the service provider in Germany.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.<br /><br /> ";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= ".</p>";



// Impressum- Modul Fehlermeldungen
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_ContentImpressum']['nopiwikmodul']     = 'Can`t find Piwik- Module!';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_ContentImpressum']['piwik_noscan']     = "<iframe class =\"piwikiframe\" frameborder=\"no\" src=\"{piwik_host}/index.php?module=CoreAdminHome&amp;action=optOut&amp;language={piwik_lang}\"></iframe>";

?>