<?php

/**
 * Contao Open Source CMS
 * 
 * Copyright (C) 2005-2012 Leo Feyer
 * 
 * @package   nlsh_easy_Piwik_Counter 
 * @author    Nils Heinold
 * @link      http://github.com/nlsh/nlsh_easy_Piwik_Counter
 * @license   LGPL 
 * @copyright Nils Heinold 
 */


/**
* Content elements
*/
$GLOBALS['TL_LANG']['CTE']['piwikImpressum']       = array('Inserts Piwik- Privacy Policy','Inserts easy Piwik- Privacy Policy.');


/**
 * Miscellaneous
 */
// Counter
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_all_title']       = 'visitors whole';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_month_title']     = 'visitors month';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_today_title']     = 'visitors today';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_yesterday_title'] = 'visitors yesterday';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_online_title']    = 'visitors online';
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_Counter']['visits_now_no_data']     = '?';


/**
 * Texte
 */
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum']  = "<p><strong>Analytics by PIWIK!<br /></strong>";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "This website uses Piwik, a web analytics open-source software.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "Piwik uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "The information generated by the cookie about your use of the website (including your IP address anonymized prior to its storage) will be stored on the server of the service provider in Germany.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.";
$GLOBALS['TL_LANG']['MSC']['piwik_Impressum'] .= "</p>";



// Impressum- Modul Fehlermeldungen
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_ContentImpressum']['nopiwikmodul']     = 'Can`t find Piwik- Module!';

// Impressum- Modul Aufruf optOut
$GLOBALS['TL_LANG']['MSC']['nlsh_easy_Piwik_ContentImpressum']['piwik_noscan']     = "<iframe class =\"piwikiframe\" frameborder=\"0\" src=\"%s/index.php?module=CoreAdminHome&amp;action=optOut&amp;language=%s&amp;css=%s\"></iframe>";
